### ISSUE TITLE
unity3d_env.py bug: done state

### ISSUE THREAD

**Issue by mrlooi** [williamd4112/gym-unity3d#2]
In unity3d_env.py, line 161:
bool((raw_data[((self.observation_space.size + self.reward_space.size))]))

will be set to True regardless of the data values.

**Comment by williamd4112** [comment]
Hi
Current workaround is using python3.

I am reorganizing the code currently.  When done, I will push to github.

**Comment by mrlooi** [comment]
or simply
np.fromstring(raw_data[self.observation_space.size + self.reward_space.size], np.bool)[0]

Anyways this repo has great stuff, keep it up
